version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: core-js
    versions:
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.2
    - 11.2.0
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.9
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.803.29
  - dependency-name: rxjs
    versions:
    - 6.6.7
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.5
  - dependency-name: karma-coverage-istanbul-reporter
    versions:
    - 3.0.3
  - dependency-name: karma
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: codelyzer
    versions:
    - 6.0.1
